# Generated by Django 3.2.8 on 2021-12-09 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_bookings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
